export default function Footer() {
  return (
    <div className="w-full h-48 text-slate-300">
      <div className="text-center mt-2 p-2">
        <p>
          This is a Web page that is generated by create-next-app , graphQL and
          apllo-client from the rick-and-morty graphQl
        </p>
        <p>
          You can find the link for the{" "}
          <a
            href="https://github.com/singh3069/rick-and-morty"
            className="text-blue-600"
          >
            Github repo here.
          </a>
          Feel free to use it.
        </p>
        <div>
          <p>You can connect me over here</p>
          <a
            href="https://www.linkedin.com/in/saurabh-rai-08536b166/"
            className="text-blue-600"
          >
            LinkedIn{" "}
          </a>
        </div>
      </div>
    </div>
  );
}
