export default function Footer() {
  return (
    <div className="w-full h-48">
      <div className="text-center pt-2">
        <p>
          This is a Web page that is generated by create-next-app , graphQL and
          apllo-client.
        </p>
        <p>
          You can find the link for the{" "}
          <a href="#" className="text-blue-600">
            Github repo here.
          </a>
          feel free to use it.
        </p>
        <div>
          <p>You can connect me over here</p>
          <span>linkdin</span>
          <span>Twitter</span>
        </div>
      </div>
    </div>
  );
}
