import type { NextPage } from "next";
import Head from "next/head";
import Characters from "../components/Characters";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  return (
    <div
      style={{
        backgroundImage: "url(/rickandmorty.png)",
        backgroundRepeat: "repeat",
        backgroundPosition: "Center",
        backgroundSize: "cover",
        height: "100%",
      }}
    >
      <div className="flex flex-col px-16">
        <Head>
          <title>Rick And Morty</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="svg" href="/rickandmorty.svg" />
        </Head>

        <header className="w-full h-20 justify-center items-center flex ">
          <h1 className="text-5xl font-semibold font-serif py-3 text-white">
            Rick And Morty
          </h1>
        </header>

        <Characters />
      </div>
      <Footer />
    </div>
  );
};

export default Home;
